#!/bin/bash

JVM_OPTS="-Xmx2g ${JVM_OPTS}"

BREAKCHARS="(){}[],^%$#@\"\";:''|\\"

START_DIR=`dirname $0`

CLOJURE_JAR="${START_DIR}"/../target/clj-standalone.jar

if [ $# -eq 0 ]; then
     rlwrap --remember -c -b "$breakchars" \
        -f "$HOME"/.clj_completions \
         java ${JVM_OPTS} -ea -cp "$CLOJURE_JAR" clojure.main
else
     # java -cp "$CLOJURE_JAR" clojure.main $1 -- "$@"
     java ${JVM_OPTS} -ea -cp "$CLOJURE_JAR" clojure.main "$@"
fi
