#!/bin/bash

JVM_OPTS="-Xmx2g ${JVM_OPTS}"

BREAKCHARS="(){}[],^%$#@\"\";:''|\\"

START_DIR=`dirname $0`

CLOJURE_JAR="${START_DIR}"/../target/clj-standalone.jar

java ${JVM_OPTS} -ea -jar "$CLOJURE_JAR" "$@"
